/**
 * Initial curated dataset of 50 major US triathlon races
 * This serves as the seed data until automated scraping is implemented
 */

import type { RawRaceData } from "./types";

export const INITIAL_US_RACES: RawRaceData[] = [
  // IRONMAN Full Distance - Major US Races
  {
    externalId: "im-cda-2025",
    name: "IRONMAN Coeur d'Alene",
    date: new Date("2025-06-22"),
    city: "Coeur d'Alene",
    state: "ID",
    distance: "full",
    registrationCost: 850,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 3800,
    bikeDistanceMeters: 180000,
    runDistanceMeters: 42195,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN World Championship",
    registrationStatus: "open",
    raceWebsiteUrl: "https://www.ironman.com/im-coeur-dalene",
  },
  {
    externalId: "im-florida-2025",
    name: "IRONMAN Florida",
    date: new Date("2025-11-01"),
    city: "Panama City Beach",
    state: "FL",
    distance: "full",
    registrationCost: 850,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 3800,
    bikeDistanceMeters: 180000,
    runDistanceMeters: 42195,
    terrain: "road",
    waterType: "ocean",
    isQualifier: true,
    qualifierFor: "IRONMAN World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im-wisconsin-2025",
    name: "IRONMAN Wisconsin",
    date: new Date("2025-09-14"),
    city: "Madison",
    state: "WI",
    distance: "full",
    registrationCost: 850,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 3800,
    bikeDistanceMeters: 180000,
    runDistanceMeters: 42195,
    elevationGainMeters: 1800,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im-texas-2025",
    name: "IRONMAN Texas",
    date: new Date("2025-04-26"),
    city: "The Woodlands",
    state: "TX",
    distance: "full",
    registrationCost: 850,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 3800,
    bikeDistanceMeters: 180000,
    runDistanceMeters: 42195,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im-arizona-2025",
    name: "IRONMAN Arizona",
    date: new Date("2025-11-16"),
    city: "Tempe",
    state: "AZ",
    distance: "full",
    registrationCost: 850,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 3800,
    bikeDistanceMeters: 180000,
    runDistanceMeters: 42195,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im-lake-placid-2025",
    name: "IRONMAN Lake Placid",
    date: new Date("2025-07-20"),
    city: "Lake Placid",
    state: "NY",
    distance: "full",
    registrationCost: 850,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 3800,
    bikeDistanceMeters: 180000,
    runDistanceMeters: 42195,
    elevationGainMeters: 2200,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN World Championship",
    registrationStatus: "open",
  },

  // IRONMAN 70.3 - Major US Races
  {
    externalId: "im703-oceanside-2025",
    name: "IRONMAN 70.3 Oceanside",
    date: new Date("2025-04-05"),
    city: "Oceanside",
    state: "CA",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "ocean",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-california-2025",
    name: "IRONMAN 70.3 California",
    date: new Date("2025-10-05"),
    city: "Sacramento",
    state: "CA",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-boulder-2025",
    name: "IRONMAN 70.3 Boulder",
    date: new Date("2025-06-08"),
    city: "Boulder",
    state: "CO",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    elevationGainMeters: 800,
    terrain: "road",
    waterType: "reservoir",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-chattanooga-2025",
    name: "IRONMAN 70.3 Chattanooga",
    date: new Date("2025-05-18"),
    city: "Chattanooga",
    state: "TN",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    elevationGainMeters: 1200,
    terrain: "road",
    waterType: "river",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-santa-rosa-2025",
    name: "IRONMAN 70.3 Santa Rosa",
    date: new Date("2025-07-12"),
    city: "Santa Rosa",
    state: "CA",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-maine-2025",
    name: "IRONMAN 70.3 Maine",
    date: new Date("2025-08-10"),
    city: "Old Orchard Beach",
    state: "ME",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "ocean",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-steelhead-2025",
    name: "IRONMAN 70.3 Steelhead",
    date: new Date("2025-08-03"),
    city: "Benton Harbor",
    state: "MI",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },

  // USA Triathlon Olympic Distance
  {
    externalId: "usat-nationals-olympic-2025",
    name: "USA Triathlon Age Group National Championships",
    date: new Date("2025-08-09"),
    city: "Milwaukee",
    state: "WI",
    distance: "olympic",
    registrationCost: 275,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "lake",
    isQualifier: false,
    registrationStatus: "open",
  },
  {
    externalId: "nyc-triathlon-2025",
    name: "New York City Triathlon",
    date: new Date("2025-07-20"),
    city: "New York",
    state: "NY",
    distance: "olympic",
    registrationCost: 350,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "river",
    registrationStatus: "open",
  },
  {
    externalId: "chicago-triathlon-2025",
    name: "Life Time Chicago Triathlon",
    date: new Date("2025-08-24"),
    city: "Chicago",
    state: "IL",
    distance: "olympic",
    registrationCost: 295,
    organizerSeries: "Life Time",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "austin-olympic-2025",
    name: "Austin Olympic Triathlon",
    date: new Date("2025-05-25"),
    city: "Austin",
    state: "TX",
    distance: "olympic",
    registrationCost: 175,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "boston-triathlon-2025",
    name: "Boston Triathlon",
    date: new Date("2025-07-27"),
    city: "Boston",
    state: "MA",
    distance: "olympic",
    registrationCost: 325,
    organizerSeries: "Columbia Threadneedle",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "ocean",
    registrationStatus: "open",
  },

  // Sprint Distance - Popular Regional Races
  {
    externalId: "san-diego-sprint-2025",
    name: "San Diego Triathlon Challenge",
    date: new Date("2025-06-01"),
    city: "San Diego",
    state: "CA",
    distance: "sprint",
    registrationCost: 125,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "ocean",
    registrationStatus: "open",
  },
  {
    externalId: "denver-sprint-2025",
    name: "Denver Sprint Triathlon",
    date: new Date("2025-07-13"),
    city: "Denver",
    state: "CO",
    distance: "sprint",
    registrationCost: 110,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    elevationGainMeters: 300,
    terrain: "road",
    waterType: "reservoir",
    registrationStatus: "open",
  },
  {
    externalId: "miami-sprint-2025",
    name: "South Beach Triathlon",
    date: new Date("2025-04-13"),
    city: "Miami",
    state: "FL",
    distance: "sprint",
    registrationCost: 135,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "ocean",
    registrationStatus: "open",
  },
  {
    externalId: "seattle-sprint-2025",
    name: "Seattle Seafair Triathlon",
    date: new Date("2025-08-03"),
    city: "Seattle",
    state: "WA",
    distance: "sprint",
    registrationCost: 145,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "phoenix-sprint-2025",
    name: "Phoenix Triathlon",
    date: new Date("2025-03-22"),
    city: "Phoenix",
    state: "AZ",
    distance: "sprint",
    registrationCost: 100,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },

  // Additional Major Regional Races
  {
    externalId: "wildflower-olympic-2025",
    name: "Wildflower Triathlon",
    date: new Date("2025-05-03"),
    city: "Bradley",
    state: "CA",
    distance: "olympic",
    registrationCost: 285,
    organizerSeries: "Tri-California Events",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    elevationGainMeters: 900,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "st-anthony-olympic-2025",
    name: "St. Anthony's Triathlon",
    date: new Date("2025-04-27"),
    city: "St. Petersburg",
    state: "FL",
    distance: "olympic",
    registrationCost: 250,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "ocean",
    registrationStatus: "open",
  },
  {
    externalId: "buffalo-springs-half-2025",
    name: "Buffalo Springs Lake 70.3",
    date: new Date("2025-06-22"),
    city: "Lubbock",
    state: "TX",
    distance: "half",
    registrationCost: 325,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "nation-capital-olympic-2025",
    name: "Nation's Triathlon",
    date: new Date("2025-09-07"),
    city: "Washington",
    state: "DC",
    distance: "olympic",
    registrationCost: 325,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "river",
    registrationStatus: "open",
  },
  {
    externalId: "escape-alcatraz-olympic-2025",
    name: "Escape from Alcatraz Triathlon",
    date: new Date("2025-06-08"),
    city: "San Francisco",
    state: "CA",
    distance: "olympic",
    registrationCost: 475,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 2400,
    bikeDistanceMeters: 29000,
    runDistanceMeters: 13000,
    elevationGainMeters: 600,
    terrain: "mixed",
    waterType: "ocean",
    registrationStatus: "waitlist",
  },

  // More Sprint Races
  {
    externalId: "portland-sprint-2025",
    name: "Portland Triathlon",
    date: new Date("2025-08-17"),
    city: "Portland",
    state: "OR",
    distance: "sprint",
    registrationCost: 130,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "dallas-sprint-2025",
    name: "Dallas Sprint Triathlon",
    date: new Date("2025-09-14"),
    city: "Dallas",
    state: "TX",
    distance: "sprint",
    registrationCost: 95,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "atlanta-sprint-2025",
    name: "Life Time Atlanta Triathlon",
    date: new Date("2025-05-18"),
    city: "Atlanta",
    state: "GA",
    distance: "sprint",
    registrationCost: 140,
    organizerSeries: "Life Time",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "minneapolis-sprint-2025",
    name: "Minneapolis Triathlon",
    date: new Date("2025-07-06"),
    city: "Minneapolis",
    state: "MN",
    distance: "sprint",
    registrationCost: 115,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "nashville-sprint-2025",
    name: "Nashville Triathlon",
    date: new Date("2025-06-14"),
    city: "Nashville",
    state: "TN",
    distance: "sprint",
    registrationCost: 105,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 750,
    bikeDistanceMeters: 20000,
    runDistanceMeters: 5000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },

  // More Olympic Distance
  {
    externalId: "philly-olympic-2025",
    name: "Philadelphia Triathlon",
    date: new Date("2025-06-22"),
    city: "Philadelphia",
    state: "PA",
    distance: "olympic",
    registrationCost: 295,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "river",
    registrationStatus: "open",
  },
  {
    externalId: "san-jose-olympic-2025",
    name: "San Jose International Triathlon",
    date: new Date("2025-09-28"),
    city: "San Jose",
    state: "CA",
    distance: "olympic",
    registrationCost: 265,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "reservoir",
    registrationStatus: "open",
  },
  {
    externalId: "raleigh-olympic-2025",
    name: "Raleigh Triathlon",
    date: new Date("2025-05-11"),
    city: "Raleigh",
    state: "NC",
    distance: "olympic",
    registrationCost: 235,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "boulder-olympic-2025",
    name: "Boulder Peak Triathlon",
    date: new Date("2025-07-20"),
    city: "Boulder",
    state: "CO",
    distance: "olympic",
    registrationCost: 275,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    elevationGainMeters: 650,
    terrain: "road",
    waterType: "reservoir",
    registrationStatus: "open",
  },

  // More 70.3 Races
  {
    externalId: "im703-austin-2025",
    name: "IRONMAN 70.3 Texas",
    date: new Date("2025-04-06"),
    city: "Galveston",
    state: "TX",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "ocean",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-oregon-2025",
    name: "IRONMAN 70.3 Oregon",
    date: new Date("2025-07-13"),
    city: "Salem",
    state: "OR",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-florida-2025",
    name: "IRONMAN 70.3 Florida",
    date: new Date("2025-04-13"),
    city: "Haines City",
    state: "FL",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-indian-wells-2025",
    name: "IRONMAN 70.3 Indian Wells",
    date: new Date("2025-12-07"),
    city: "Indian Wells",
    state: "CA",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },
  {
    externalId: "im703-des-moines-2025",
    name: "IRONMAN 70.3 Des Moines",
    date: new Date("2025-06-15"),
    city: "Des Moines",
    state: "IA",
    distance: "half",
    registrationCost: 425,
    organizerSeries: "IRONMAN",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "lake",
    isQualifier: true,
    qualifierFor: "IRONMAN 70.3 World Championship",
    registrationStatus: "open",
  },

  // Additional Regional Favorites
  {
    externalId: "columbia-olympic-2025",
    name: "Columbia Triathlon",
    date: new Date("2025-09-21"),
    city: "Columbia",
    state: "MD",
    distance: "olympic",
    registrationCost: 245,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "gulf-coast-half-2025",
    name: "Gulf Coast Half",
    date: new Date("2025-05-04"),
    city: "Panama City Beach",
    state: "FL",
    distance: "half",
    registrationCost: 295,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "ocean",
    registrationStatus: "open",
  },
  {
    externalId: "pacific-grove-olympic-2025",
    name: "Pacific Grove Triathlon",
    date: new Date("2025-09-13"),
    city: "Pacific Grove",
    state: "CA",
    distance: "olympic",
    registrationCost: 225,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "ocean",
    registrationStatus: "open",
  },
  {
    externalId: "alcatraz-aquathlon-2025",
    name: "Alcatraz Aquathlon",
    date: new Date("2025-10-12"),
    city: "San Francisco",
    state: "CA",
    distance: "sprint",
    registrationCost: 195,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 2400,
    runDistanceMeters: 13000,
    terrain: "mixed",
    waterType: "ocean",
    registrationStatus: "open",
  },
  {
    externalId: "vineman-half-2025",
    name: "Vineman 70.3",
    date: new Date("2025-07-19"),
    city: "Santa Rosa",
    state: "CA",
    distance: "half",
    registrationCost: 395,
    organizerSeries: "Vineman Inc",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "river",
    registrationStatus: "open",
  },
  {
    externalId: "tahoe-olympic-2025",
    name: "Lake Tahoe Triathlon",
    date: new Date("2025-09-21"),
    city: "South Lake Tahoe",
    state: "CA",
    distance: "olympic",
    registrationCost: 285,
    organizerSeries: "Big Blue Adventure",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    elevationGainMeters: 700,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
  {
    externalId: "miami-half-2025",
    name: "Miami Half Ironman",
    date: new Date("2025-10-26"),
    city: "Miami",
    state: "FL",
    distance: "half",
    registrationCost: 350,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1900,
    bikeDistanceMeters: 90000,
    runDistanceMeters: 21097,
    terrain: "road",
    waterType: "ocean",
    registrationStatus: "open",
  },
  {
    externalId: "madison-olympic-2025",
    name: "Madison Sprint & Olympic Triathlon",
    date: new Date("2025-08-24"),
    city: "Madison",
    state: "WI",
    distance: "olympic",
    registrationCost: 215,
    organizerSeries: "USA Triathlon",
    swimDistanceMeters: 1500,
    bikeDistanceMeters: 40000,
    runDistanceMeters: 10000,
    terrain: "road",
    waterType: "lake",
    registrationStatus: "open",
  },
];
